jobs:
  include:
    - stage: CMake build and CTest
      language: minimal
      script:
        - set -e

        - echo 'Installing build toolchain...' && echo -en 'travis_fold:start:install\\r'
        - sudo apt update
        - sudo apt install g++ cmake cppcheck
        - echo -en 'travis_fold:end:install\\r'

        - echo 'Lint project' && echo -en 'travis_fold:start:lint\\r'
        - cppcheck --enable=all --suppressions-list=suppressions.txt --inline-suppr --inconclusive --force --error-exitcode=1 src/
        - echo -en 'travis_fold:end:lint\\r'

        - echo 'Build project' && echo -en 'travis_fold:start:build\\r'
        - mkdir build
        - cd build
        - cmake -DBUILD_TESTING="ON" ../
        - cmake --build .
        - echo -en 'travis_fold:end:build\\r'

        - echo 'Test project' && echo -en 'travis_fold:start:test\\r'
        - ctest
        - echo -en 'travis_fold:end:test\\r'
